apps/foreas/urls.py
from django.urls import path
from . import views
# from .charts import *
# from . import export

#class based views
from .views import ForeasListView,ForeasListViewVisibleFalse,EpafiListView
# from .delete_records import AithmaDeleteView,ForeasDeleteView,ContactDeleteView,ErgasiaDeleteView,AdeiaDeleteView,ServiceDeleteView,SellCornfirmDelete,TrainingDeleteView,HardwareDeleteView
# from .search import HomePageSearchListView
# from .update_records import AdeiaUpdateView

urlpatterns = [

    path('acs-services/foreas', ForeasListView.as_view(), name='pelatis'),
    path('acs-services/foreas-in-active', ForeasListViewVisibleFalse.as_view(), name='in_active_pelatis'),
    path('acs-services/edit/<int:dhmos_id>/',views.edit_forea, name='edit_forea'),
    path('acs-services/delete/<int:pk>/', views.soft_delete_dhmos, name='soft_delete_dhmos'),
    path('acs-services/restore/<int:pk>/', views.restore_dhmos, name='restore_dhmos'),
    path('acs-services/contacts/', EpafiListView.as_view(), name='contact'),
    path('acs-services/edit/contact/<int:employee_id>/',views.edit_contact, name='edit_contact'),
#     path('acs-services/update/contact/<int:pk>/',views.epafi_update, name='epafi_update'),
#     path('acs-services/carrier/tasks', ErgasiesListView.as_view(), name='ergasia'),
#     path('acs-services/update/task/<int:pk>/',views.ergasia_update, name='ergasia_update'),
#     path('acs-services/update/new_task/<int:pk>/',views.ergasia_copy_paste, name='ergasia_copy_paste'),
#     path('acs-services/carrier/days-off', AdeiaListView.as_view(), name='adeia'),
#     path('acs-services/update/days-off/<int:pk>/',AdeiaUpdateView.as_view(), name='adeia_update'),
#     path('acs-services/carrier/requests', AithmataListView.as_view(), name='aithma'),
#     path('acs-services/update/request/<int:pk>/',views.aithma_update, name='aithma_update'),
#     path('acs-services/carrier/sales', PolisiListView.as_view(), name='polisi'),
#     path('acs-services/update/sales/<int:pk>/',views.polisi_update, name='polisi_update'),
#     path('acs-services/carrier/service', ServiceListView.as_view(), name='service'),
#     path('acs-services/update/service/<int:pk>/',views.service_update, name='service_update'),
#     path('acs-services/carrier/hardware', HardwareListView.as_view(), name='hardware'),
#     path('acs-services/update/hardware/<int:pk>/',views.hardware_update, name='hardware_update'),
#     path('acs-services/carrier/training', TrainingListVew.as_view(), name='training'),
#     path('acs-services/update/training/<int:pk>/',views.training_update, name='training_update'),
#     path('acs-services/carrier/software', SoftwareListView.as_view(), name='software'),
#     path('password_reset', views.password_reset_request, name="password_reset"),
#     #search
#     path('acs-services/search/tasks-search',ErgasiesSearchListView.as_view(), name='ergasia_search'),
#     path('acs-services/search/sales-search',SalesSearchListView.as_view(), name='polisi_search'),
#     path('acs-services/search/day-off-search', DayOffSearchListView.as_view(), name='dayoff_search'),
#     #add new records
#     path('acs-services/new/client',views.dhmospost_new, name='pelatis_new'),
#     path('acs-services/new/contact',views.epafi_new, name='epafi_new'),
#     path('acs-services/new/task',views.ergasia_new, name='ergasia_new'),
#     path('acs-services/new/day-off',views.adeia_new, name='adeia_new'),
#     path('acs-services/new/request',views.aithma_new, name='aithma_new'),
#     path('acs-services/new/sale',views.polisi_new, name='polisi_new'),
#     path('acs-services/new/service',views.service_new, name='service_new'),
#     path('acs-services/new/training',views.training_new, name='training_new'),
#     path('acs-services/new/hardware',views.hardware_new, name='hardware_new'),
#     # delete records
#     path('delete-pelatis/<int:pk>/',ForeasDeleteView.as_view(), name='delete_pelatis'),
#     path('delete-epafi/<int:pk>/', ContactDeleteView.as_view(), name='delete_epafi'),
#     path('delete-ergasia/<int:pk>/',ErgasiaDeleteView.as_view(), name='delete_ergasia'),
#     path('delete_adeia/<int:pk>/', AdeiaDeleteView.as_view(), name='delete_adeia'),
#     path('delete_aithma/<int:pk>/', AithmaDeleteView.as_view(), name='delete_aithma'),
#     path('delete_polisi/<int:pk>/', SellCornfirmDelete.as_view(), name='delete_polisi'),
#     path('delete_service/<int:pk>/',ServiceDeleteView.as_view(), name='delete_service'),
#     path('delete_training/<int:pk>/',TrainingDeleteView.as_view(), name='delete_training'),
#     path('delete_hardware/<int:pk>/',HardwareDeleteView.as_view(), name='delete_hardware'),
#     # chained selection ergasia_new
#     path('api/ergasies/dhmoi-epafes/<int:pk>/', views.api_dhmos, name='api_dhmos'),
#     path('api/ergasies-update/dhmoi-epafes/<int:pk>/', views.api_dhmos_update, name='api_dhmos_update'),
#     path('api/aithmata/dhmoi-epafes/<int:pk>/', views.api_aithma, name='api_aithma'),
#     # path(r'api/prosfora/dhmoi-epafes/<int:pk>/', timologisi.views.api_dhmos_prosfora, name='api_dhmos_prosfora'),
#     # charts
#     path('acs-services/day-off-charts', AdeiaChartView.as_view(), name='adeia_chart'),
#     path('acs-services/sales-chart', PolisiChartView.as_view(), name='polisi_chart'),
#     path('acs-services/task-chart', ErgasiaChartView.as_view(), name='ergasia_chart'),
#     # export csv,xls
#     path('acs-services/export-employees-xls/', views.export_epafes, name='export'),
#     path('acs-services/export-employees-csv/csv', views.employees_csv_export, name='export_csv'),
#     path('acs-services/export-ergasies/', views.export_ergasies, name='export_ergasies'),
#     path('acs-services/export-ergasies-all/', views.export_ergasies_all, name='export_ergasies_all'),
#     path('acs-services/export-adeies-all/', views.export_adeies_all, name='export_adeies_all'),
#     path('acs-services/search_items/', search_items, name='search_items'),
 ]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('organization.urls'))
]

apps/organization/models.py
from django.db import models
from django.urls import reverse
from .model_choices import *
import datetime
from django.db.models import Sum
from django_extensions.db.models import TimeStampedModel

class VisibilityManager(models.Manager):
    """
    Custom manager to handle visibility filters.
    """

    def get_queryset(self) -> models.QuerySet:
        """
        Override the default queryset to include all records.
        """
        return super().get_queryset()

    def visible(self) -> models.QuerySet:
        """
        Return only records where is_visible=True.
        """
        return self.get_queryset().filter(is_visible=True)

    def invisible(self) -> models.QuerySet:
        """
        Return only records where is_visible=False.
        """
        return self.get_queryset().filter(is_visible=False)


class Organization(TimeStampedModel):
    name = models.CharField(max_length=100, verbose_name='Πελάτης')
    address = models.CharField(max_length=100, verbose_name='Διεύθυνση')
    city = models.CharField(max_length=100, verbose_name='Πόλη')
    phone = models.CharField(max_length=100, verbose_name='Τηλέφωνο')
    fax = models.CharField(max_length=50, verbose_name='Fax')
    teamviewer = models.CharField(max_length=60, verbose_name='TeamViewer')
    email = models.EmailField()
    website = models.URLField(max_length=250)
    info = models.TextField(max_length=1000, verbose_name='Πληροφορίες')
    is_visible = models.BooleanField(default=False, verbose_name='Κατάσταση')
    old_id = models.IntegerField(verbose_name='old_id',null=True,blank=True)

    class Meta:
        verbose_name = 'ACS Φορέας'
        verbose_name_plural = 'ACS Φορέας'
        ordering = ['name']

    # Custom managers
    objects = VisibilityManager()  # Filters only active objects

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        """Soft delete the object by marking it as visible=false."""
        self.is_visible = False
        self.save()

    def restore(self, *args, **kwargs):
        """Soft delete the object by marking it as visible=true."""
        self.is_visible = True
        self.save()



class Employee(TimeStampedModel):
    organization = models.ForeignKey('Organization', on_delete=models.CASCADE, verbose_name='Πελάτης', null=True)
    firstname = models.CharField(max_length=150, verbose_name='Όνομα', null=True)
    lastname = models.CharField(max_length=150, verbose_name='Επώνυμο', null=True)
    tmhma = models.CharField(max_length=100, choices=tmhma_choice,verbose_name='Υπηρεσία', blank=True, null=True,)
    phone = models.CharField(max_length=100, verbose_name='Τηλέφωνο', blank=False)
    cellphone = models.CharField(max_length=30, verbose_name='Κινητό', blank=True)
    email = models.EmailField(blank=True, null=True)
    secondary_email = models.EmailField(blank=True, null=True)
    info = models.TextField(max_length=1000, verbose_name='Πληροφορίες', blank=True)
    is_visible = models.BooleanField(default=False, verbose_name='Κατάσταση')
    old_id = models.IntegerField(verbose_name='old_id', null=True, blank=False)

    class Meta:
        verbose_name = 'ACS Στοιχεία Επικοινωνίας Υπαλλήλων'
        verbose_name_plural = 'ACS Στοιχεία Επικοινωνίας Υπαλλήλων'

    def __str__(self):
        return f"{self.lastname} {self.firstname}"

    # Custom managers
    objects = VisibilityManager()  # Filters only active objects

    def delete(self, *args, **kwargs):
        """Soft delete the object by marking it as visible=false."""
        self.is_visible = False
        self.save()

    def restore(self, *args, **kwargs):
        """Soft delete the object by marking it as visible=true."""
        self.is_visible = True
        self.save()


class Ergasies(TimeStampedModel):
    organization = models.ForeignKey('Organization', on_delete=models.CASCADE, verbose_name='Πελάτης')
    importdate = models.DateField(default=datetime.date.today, verbose_name='Ημ. Κατ.', db_index=True)
    app = models.CharField(max_length=100, choices=app_choice,verbose_name='Εφαρμογή', blank=True)
    jobtype = models.CharField(max_length=100, choices=job_choice,verbose_name='Τύπος Εργασίας', default='TeamViewer')
    info = models.TextField(max_length=1000, verbose_name='Περιγραφή')
    text = models.TextField(max_length=1000, verbose_name='Σημειώσεις', blank=True)
    employee= models.ForeignKey('accounts.User', max_length=100, verbose_name='Υπάλληλος',on_delete=models.CASCADE)  # delete kai
    time = models.FloatField(verbose_name='Διάρκεια',null=True, blank=True)
    org_employee = models.ForeignKey('Employee', on_delete=models.CASCADE, verbose_name='Πελάτης',null=True, blank=False)
    ticketid = models.CharField(max_length=50, verbose_name='Αίτημα OTS', blank=True)
    old_id = models.IntegerField(verbose_name='old_id', null=True, blank=True)
    
    class Meta:
        indexes = [models.Index(fields=['importdate', 'employee'])]
        verbose_name = 'ACS Εργασίες Φορέα'
        verbose_name_plural = 'ACS Εργασίες Φορέα'
        ordering = ['importdate']
    
    def __str__(self):
        return str(self.id)
    
    def total_work_time(self):  # Ώρες εργασίας ανα χρήστη
        today = datetime.date.today()
        return Ergasies.objects.all().filter(importdate__year=today.year, employee=self.employee).aggregate(time_all=Sum('time')).get('time_all')

    def get_symbasi(self):
        return ",".join([str(p) for p in self.symbasi.all()])

    # def get_absolute_url(self):
    #     return reverse('ergasia_update', args=[str(self.id)])
    
    # def get_absolute_url_copy_paste(self):
    #     return reverse('ergasia_copy_paste', args=[str(self.id)])

    def get_absolute_url_delete(self):
        return reverse('delete_ergasia', args=[str(self.id)])



class Department(TimeStampedModel):
    name = models.CharField(max_length=255, null=False, blank=False, db_index=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Κατάσταση')
    
    class Meta:
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Υπηρεσίες Οργανισμών'
        verbose_name_plural = 'Υπηρεσίες Οργανισμών'
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"




class Application(TimeStampedModel):
    title = models.CharField(max_length=255, null=False, blank=False, db_index=True)
    description = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Κατάσταση')
    
    class Meta:
        indexes = [models.Index(fields=['title'])]
        verbose_name = 'OTS Εφαρμογές'
        verbose_name_plural = 'OTS Εφαρμογές'
        ordering = ['title']

    def __str__(self):
        return f"{self.title}"

templates/apps/foreas/contact.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% load custom_filters %}
{% load i18n %}

{% block content %}

<!--Filter Form-->
<form method="get" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-3">
    {% csrf_token %}
    {{ filter.form }}
    <button type="submit" class="block text-center sm:w-44 py-2 border text-gray-700 bg-yellow-400 hover:bg-yellow-500 rounded-lg focus:ring-indigo-600 focus:border-indigo-600 sm:text-sm font-bold">Αναζήτηση</button>
</form>
<!--End Filter Form-->

<div class="divider divider-primary"></div>

<!--Buttons-->
<div class="">
    <a href="#"
       class="px-4 py-2.5 text-sm font-medium text-white transition-all duration-200 bg-indigo-600 hover:bg-indigo-700  rounded-lg group"
       title="Νέα εγγραφή">Νέα εγγραφή</a>
    <a class="px-4 py-2.5 text-sm font-medium text-white transition-all duration-200 bg-green-600 hover:bg-green-700 rounded-lg group"
       href="#"
       title="Νέα εγγραφή">Export</a>
</div>

<!--End Buttons-->


<!--Φορέας Λίστα-->
<div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-5">
    <div class="hidden sm:block">
        <table class="w-full text-sm text-center rtl:text-right text-gray-500 dark:text-white">
            <thead class="text-xs odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b">
                <tr>
                    <th colspan="10" class="text-center text-2xl font-bold">Πελάτες</th>
                </tr>
                <tr>
                    <th scope="col" class="px-4 py-2">Φορέας</th>
                    <th scope="col" class="px-4 py-2">Επώνυμο</th>
                    <th scope="col" class="px-4 py-2">Όνομα</th>
                    <th scope="col" class="px-4 py-2">Τμήμα</th>
                    <th scope="col" class="px-4 py-2">Τηλέφωνο</th>
                    <th scope="col" class="px-4 py-2">Κινητό</th>
                    <th scope="col" class="px-4 py-2">Email</th>
                    <th scope="col" class="px-4 py-2">2ο Email</th>
                    <th scope="col" class="px-4 py-2">Κατάσταση</th>
                    <th scope="col" class="px-4 py-2">Ενέργειες</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in epafi_list %}
                <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b ">
                    <td class="px-4 py-2 border-b" data-label="Φορέας">{{employee.organization }}</td>
                    <td class="px-4 py-2" data-label="Διεύθυνση">
                        <input type="text" value="{{employee.lastname }}" class="w-full bg-transparent border-none text-center text-sm rounded-md" id="lastname-{{ employee.id }}"></td>
                    <td class="px-4 py-2" data-label="Διεύθυνση">
                        <input type="text" value="{{employee.firstname }}" class="w-full bg-transparent border-none text-center text-sm rounded-md" id="firstname-{{ employee.id }}"></td>
                    <td class="px-4 py-2" data-label="Πόλη">
                        <input type="text" value="{{employee.get_tmhma_display }}" class="w-full bg-transparent border-none text-center text-sm rounded-md" id="tmhma-{{ employee.id }}"></td>
                    <td class="px-4 py-2" data-label="Τηλέφωνο">
                        <input type="text" value="{{employee.phone }}" class="w-full bg-transparent border-none text-center text-sm rounded-md" id="phone-{{ employee.id }}"></td>
                    <td class="px-4 py-2" data-label="Τηλέφωνο">
                        <input type="text" value="{{employee.cellphone }}" class="w-full bg-transparent border-none text-center text-sm rounded-md" id="cellphone-{{ employee.id }}"></td>
                        <td class="px-4 py-2" data-label="Email">
                            <input 
                                type="text" 
                                value="{{ employee.email }}" 
                                class="w-full bg-transparent border-none text-center text-sm rounded-md overflow-visible" 
                                id="email-{{ employee.id }}"
                                style="width: auto; white-space: nowrap; overflow: visible;">
                        </td>
                    <td class="px-4 py-2" data-label="Email">
                        <input type="text" value="{{employee.secondary_email }}" class="w-full bg-transparent border-none text-center text-sm rounded-md" id="secondary_email-{{ employee.id }}"></td>
                    <td class="px-4 py-2 text-green-500 font-bold" data-label="Κατάσταση">
                        <input type="checkbox" class="form-checkbox h-5 w-5 text-green-600" id="is_visible-{{ employee.id }}" 
                            {% if employee.is_visible %} checked {% endif %}></td>
                        <td class="px-4 py-2" data-label="Ενέργειες">
                            <div class="flex space-x-2">
                                <a href="{% url 'soft_delete_contact' employee.pk %}" 
                                    class="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-lg dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800" 
                                    onclick="return confirm('Είστε σίγουροι για την απενεργοποίηση της επαφής;');">Del</a>
                                <button onclick="saveChanges({{ employee.id }})" 
                                    class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-800">Save</button>
                            </div>
                        </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
<!-- Cards for smaller screens -->
<div class="block sm:hidden space-y-4">
    {% for employee in epafi_list %}
        <div class="border p-4 rounded-lg shadow-md bg-white">
            <p><span class="font-bold text-gray-700 mr-2">Φορέας:</span>{{dhmos.name|title|default_if_none:""}}</p>
            <p><span class="font-bold text-gray-700 mr-2">Επώνυμο:</span> {{dhmos.address}}</p>
            <p><span class="font-bold text-gray-700 mr-2">Όνομα:</span> {{dhmos.city}}</p>
            <p><span class="font-bold text-gray-700 mr-2">Τμήμα:</span>{{dhmos.phone}}</p>
            <p><span class="font-bold text-gray-700 mr-2">Τηλέφωνο:</span>{{dhmos.email}}</p>
            <p><span class="font-bold text-gray-700 mr-2">Κινητό:</span>{{dhmos.website| remove_protocol}}</p>
            <p><span class="font-bold text-gray-700 mr-2">Email:</span>{{dhmos.email}}</p>
            <p><span class="font-bold text-gray-700 mr-2">2ο Email:</span>{{dhmos.email}}</p>
            <p><span class="font-bold text-gray-700 mr-2"></span> 
            {% if employee.is_visible == True %}
                <td class="px-4 py-2 text-green-500 font-bold" data-label="Κατάσταση">Online</td>
            {% else %}
                <td class="px-4 py-2 text-red-600 font-bold">Offline
            {% endif %}</p>
        </div>
    {% endfor %}
</div>
</div>
<!--End Cards-->
<!-- Centered Pagination Controls -->
<div class="flex justify-center items-center mt-6 space-x-2">
    <!-- Previous Page Link -->
    {% if page_obj.has_previous %}
        <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value|urlencode }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}" 
           class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 font-medium">
           Previous
        </a>
    {% else %}
        <span class="px-4 py-2 bg-gray-100 text-gray-400 rounded font-medium">Previous</span>
    {% endif %}

    <!-- Page Numbers -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <span class="px-4 py-2 bg-blue-700 text-white rounded font-medium">{{ num }}</span>
        {% else %}
            <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value|urlencode }}&{% endif %}{% endfor %}page={{ num }}" 
               class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 font-medium">
               {{ num }}
            </a>
        {% endif %}
    {% endfor %}

    <!-- Next Page Link -->
    {% if page_obj.has_next %}
        <a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value|urlencode }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}" 
           class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 font-medium">
           Next
        </a>
    {% else %}
        <span class="px-4 py-2 bg-gray-100 text-gray-400 rounded font-medium">Next</span>
    {% endif %}
</div>
<!--End Center pagination Controlss-->

<script>
    function saveChanges(employeeId) {
        const firstname = document.getElementById(`firstname-${employeeId}`).value;
        const lastname = document.getElementById(`lastname-${employeeId}`).value;
        const tmhma = document.getElementById(`tmhma-${employeeId}`).value;
        const phone = document.getElementById(`phone-${employeeId}`).value;
        const cellphone = document.getElementById(`cellphone-${employeeId}`).value;
        const email = document.getElementById(`email-${employeeId}`).value;
        const secondary_email = document.getElementById(`secondary_email-${employeeId}`).value;
        
        const isVisible = document.getElementById(`is_visible-${employeeId}`).checked;

        fetch(`/acs-services/edit/contact/${employeeId}/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
            },
            body: JSON.stringify({
                firstname: firstname,
                lastname: lastname,
                tmhma: tmhma,
                phone: phone,
                cellphone: cellphone,
                email: email,
                secondary_email: secondary_email,
                
                is_visible: isVisible,

            }),
        })
        .then(response => response.json())
        .then(data => {
            alert('Contact updated successfully!');
            // Optionally, update the UI here without a page reload
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Failed to update contact');
        });
    }
</script>

{% endblock %}