apps/accounts/urls.py
# accounts/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import EmailAuthenticationForm
from . import views
from .views import adeia_list,AcsProfile

urlpatterns = [
    path('accounts/login/', views.custom_login_view, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('accounts/password_change/', views.password_change, name='password_change'),
    path('accounts/update-profile/', views.update_profile, name='update_profile'),
    
    #acs_employees
    path("acs/adeia", views.adeia_list, name="acs-adeies"),
    path("acs/user/profile", AcsProfile.as_view(), name="profile")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('', include('organization.urls'))
]

apps/accounts/models.py
# accounts/models.py

import datetime
from django.db.models import Sum
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel
from django.urls import reverse
from .model_choices import *
from django.db.models import Q

class Company(TimeStampedModel):
    company_owner_name = models.CharField(max_length=255)
    company_title = models.CharField(max_length=255)
    company_title_alias = models.CharField(max_length=255, unique=True)
    company_address = models.CharField(max_length=255)
    company_city = models.CharField(max_length=100)
    company_postal_code = models.CharField(max_length=20)
    company_country = models.CharField(max_length=100)
    company_phone_number_1 = models.CharField(max_length=255)
    company_phone_number_2 = models.CharField(max_length=255)
    company_email = models.EmailField(max_length=254)
    company_is_active = models.BooleanField(default=True)
    
    
    
    class Meta:
        ordering = ['company_title']
        verbose_name = _('Εταιρεία')
        verbose_name_plural = _('Εταιρεία')
    
    def __str__(self):
        return f"{self.company_title}"



class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if not extra_fields.get('is_staff'):
            raise ValueError('Superuser must have is_staff=True.')
        if not extra_fields.get('is_superuser'):
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin,TimeStampedModel):
    company = models.ManyToManyField(Company, related_name="users")
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    sex_choice = models.CharField(max_length=10, choices=sex_choice, verbose_name='Φύλο', blank=True)
    job_title = models.CharField(max_length=60, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=15, unique=True,null=True, blank=True)
    days_sum = models.IntegerField(verbose_name="Ημέρες άδειας", null=False, blank=False, default='0')
    days_left = models.IntegerField(verbose_name="Υπόλοιπο προηγούμενου έτους", null=False, blank=False, default='0')
    first_login = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def total(self):  # Προσθέτει τον αριθμό ημερών άδειας του εργαζομένου με το υπόλοιπο του προηγούμενου έτους
        return self.days_sum + self.days_left

    def remaining_days(self): # Παίρνει το σύνολο ημερων απο το πρηγουμενο και τρεχον έτος και αφαιρεί μέρες άδειας που έχουν χρησιμοποιηθεί
        total_days = self.total()
        used_days = Adeia.objects.filter(acs_employee=self).aggregate(Sum('days'))['days__sum'] or 0
        return total_days - used_days


class Adeia(TimeStampedModel):
    acs_employee = models.ForeignKey('User', max_length=100, verbose_name='Υπάλληλος', on_delete=models.CASCADE)
    adeiatype = models.CharField(max_length=1,choices=adeia_choice, verbose_name='Τύπος Άδειας')
    startdate = models.DateField(default=datetime.date.today, verbose_name='Από')
    enddate = models.DateField(default=datetime.date.today, verbose_name='Έως')
    days = models.IntegerField(verbose_name='Ημέρες', null=False, blank=False, default='0')

    class Meta:
        indexes = [models.Index(fields=['created', 'acs_employee'])]
        verbose_name = 'ACS Άδειες'
        verbose_name_plural = 'ACS Άδειες'

    # def total(self):  # Προσθέτει τις μέρες άδειας του τρέχοντος έτους
    #     today = datetime.date.today()
    #     return self.__class__.objects.all().filter(createddate__year=today.year, acs_employee=self.acs_employee).exclude(Q(adeiatype='2') | Q(adeiatype='4')).aggregate(
    #         sum_all=Sum('days')).get('sum_all') or 0

    # def anarotiki_total(self):
    #     today = datetime.date.today()
    #     return self.__class__.objects.all().filter(createddate__year=today.year, acs_employee=self.acs_employee, adeiatype='2').aggregate(
    #         sum_all=Sum('days')).get('sum_all')

    # def goniki_total(self):
    #     today = datetime.date.today()
    #     return self.__class__.objects.all().filter(createddate__year=today.year, acs_employee=self.acs_employee, adeiatype='4').aggregate(
    #         sum_all=Sum('days')).get('sum_all')

    # def kanoniki_total(self):
    #     today = datetime.date.today()
    #     return self.__class__.objects.all().filter(createddate__year=today.year, acs_employee=self.acs_employee, adeiatype='1').aggregate(
    #         sum_all=Sum('days')).get('sum_all')

    def get_absolute_url(self):
        return reverse('adeia_update', args=[str(self.id)])

    def get_absolute_url_delete(self):
        return reverse('delete_adeia', args=[str(self.id)])



class Training(TimeStampedModel):
    company = models.CharField(max_length=100, choices=TrainingChoice.choices, verbose_name='Φορέας', default='OTS')
    place = models.CharField(max_length=100, choices=training_place, verbose_name='Χώρος', default='-')
    importdate = models.DateField(default=datetime.date.today, verbose_name='Καταχώρηση')
    training_type = models.CharField(max_length=100, choices=training_choice, verbose_name='Εκαπίδευση', blank=False, default='Εκπαίδευση')
    app = models.CharField(max_length=100, choices=app_choice,verbose_name='Εφαρμογή', blank=True)
    time = models.FloatField(verbose_name='Διάρκεια')
    acs_employee = models.ForeignKey('User', max_length=100, verbose_name='Υπάλληλος', on_delete=models.CASCADE)
    info = models.TextField(max_length=500, verbose_name='Περιγραφή', null=True, blank=True)

    class Meta:
        indexes = [models.Index(fields=['importdate', 'acs_employee'])]
        verbose_name = 'ACS Εκπαιδεύσεις'
        verbose_name_plural = 'ACS Εκπαιδεύσεις'

    def get_absolute_url(self):
        return reverse('training_update', args=[str(self.id)])

    def get_absolute_url_delete(self):
        return reverse('delete_training', args=[str(self.id)])

apps/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .forms import AdeiaForm, EmailAuthenticationForm, UserUpdateForm
from .password_change import password_change
from django_filters.views import FilterView
from django.views.generic import TemplateView
from .models import Adeia
from .filters import AdeiaFilter
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import JsonResponse
import datetime

# Login user function


def custom_login_view(request):
    if request.method == 'POST':
        form = EmailAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                # Redirect to home page after successful login
                return redirect('home')
        else:
            # If the form is invalid, the error message will be shown on the form
            return render(request, 'apps/accounts/login.html', {'form': form})
    else:
        form = EmailAuthenticationForm()
    return render(request, 'apps/accounts/login.html', {'form': form})


# Logout user function
def custom_logout(request):
    logout(request)
    return redirect('login')


##########################################################################

def adeia_list(request):
    today = datetime.date.today()

    adeia_list = Adeia.objects.filter(
        startdate__year=today.year, acs_employee=request.user)
    adeia_filter = AdeiaFilter(request.GET, queryset=adeia_list)

    paginator = Paginator(adeia_filter.qs, 10)  # 10 tasks per page
    # Get the page number from the request
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Copy request.GET to preserve existing filters
    filter_params = request.GET.copy()
    if filter_params.get('page'):
        filter_params.pop('page')
    form = AdeiaForm()
    show_modal = False
    if request.method == "POST":
        form = AdeiaForm(request.POST)
        if form.is_valid():
            form.author = request.user
            form.save()
            return JsonResponse({"success": True})
        else:
            return JsonResponse({"success": False, "errors": form.errors})
    else:
        form = AdeiaForm(initial={'acs_employee': request.user})

    context = {
        'page_obj': page_obj,
        'filter': adeia_filter,
        'filter_params': filter_params.urlencode(),
        'form': form,
        'show_modal': show_modal,
    }
    return render(request, 'apps/accounts/adeia.html', context)


class AcsProfile(LoginRequiredMixin, TemplateView):
    template_name = "apps/accounts/profile.html"


def update_profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your phone number has been updated.')
            # Change 'profile' to your desired redirect URL
            return redirect('profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = UserUpdateForm(instance=request.user)

    return render(request, 'apps/accounts/profile.html', {'form': form})

templates/apps/accounts/adeia.html
{% extends "_base.html" %}
{% load widget_tweaks %}
{% load custom_filters %}
{% load i18n %}


{% block content %}

<!--Filter Form-->
<form methid="get" action="#"" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-3">
  {% csrf_token%}
  {{ filter.form }}
  <button type="submit" class="block text-center mt-1 sm:w-44 py-2 border text-gray-700 bg-yellow-400 hover:bg-yellow-500 rounded-lg focus:ring-indigo-600 focus:border-indigo-600 sm:text-sm font-bold">Αναζήτηση</button>
</form>  
<!--End Filter Form-->

<div class="divider divider-primary"></div>

<!--Buttons-->
<div class="flex flex-col sm:flex-row gap-3 mt-3">
  <button id="openModal" class="px-4 py-2 text-base md:px-2 md:py-2 md:text-sm bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-medium">Καταχώρηση άδειας</button>
  <div class="ml-auto flex gap-3">
    <span class="p-1.5 text-base font-medium tracking-wider text-gray-700 dark:text-white ">Υπόλοιπο προηγ. έτους - {{user.days_left}}  </span>
    <span class="p-1.5 text-base font-medium tracking-wider text-gray-700 dark:text-white ">Δικαιούμενες ημέρες έτους - {{user.total}} </span>
    <span class="p-1.5 text-base font-medium tracking-wider text-red-600 dark:text-white ">Υπόλοιπο - {{ user.remaining_days }} </span>
  </div>
</div>
<!--End Buttons-->

<!--Adeies List-->
<div class="h-screen hidden sm:block mt-3">
  <div class="overflow-auto rounded-lg shadow">
    <table class="w-full text-sm text-center rtl:text-right text-gray-500 dark:text-white">
      <caption class="caption-top font-bold text-white bg-blue-700 bg-opacity-90">
        Άδειες εργαζομένων
      </caption>
      <thead class="text-xs odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b">
        <tr>
        </tr>
          <tr>
            <th scope="col" class="px-4 py-2">ACS</th>
            <th scope="col" class="px-4 py-2">Κατηγορία Άδειας</th>
            <th scope="col" class="px-4 py-2">Έναρξη</th>
            <th scope="col" class="px-4 py-2">Λήξη</th>
            <th scope="col" class="px-4 py-2">Ημέρες</th>
            <th scope="col" class="px-4 py-2">Ενέργειες</th>
          </tr>
      </thead>
      <tbody>
        {% for adeia in page_obj %}
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b ">
          <td class="px-4 py-2 border-b text-sm text-gray-700 whitespace-nowrap dark:text-white" data-laber="acs">
            {{adeia.acs_employee.last_name}}&nbsp{{adeia.acs_employee.first_name}}
          </td>
          <td class="px-4 py-2 border-b text-sm text-gray-700 whitespace-nowrap dark:text-white" data-laber="acs">
            <input type="text" value="{{adeia.get_adeiatype_display}}" class="w-ful bg-transparent border-none text-center text-sm rounded-md" id="adeiatype-{{adeia.id}}">
          </td>
          <td class="px-4 py-2 border-b text-sm text-gray-700 whitespace-nowrap dark:text-white" data-laber="acs">
            <input type="text" value="{{adeia.startdate|date:'d/m/Y'}}" class="w-ful bg-transparent border-none text-center text-sm rounded-md" id="startdate-{{adeia.id}}">
          </td>
          <td class="px-4 py-2 border-b text-sm text-gray-700 whitespace-nowrap dark:text-white" data-laber="acs">
            <input type="text" value="{{adeia.enddate|date:'d/m/Y'}}" class="w-ful bg-transparent border-none text-center text-sm rounded-md" id="enddate-{{adeia.id}}">
          </td>
          <td class="px-4 py-2 border-b text-sm text-gray-700 whitespace-nowrap dark:text-white" data-laber="acs">
            <input type="text" value="{{adeia.days}}" class="w-ful bg-transparent border-none text-center text-sm rounded-md" id="days-{{adeia.id}}">
          </td>
          <td class="px-4 py-2" data-label="Ενέργειες">
            <div class="flex justify-center space-x-2">
            <a href="#" class="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-lg dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800" 
            onclick="return confirm('Είστε σίγουροι για την απενεργοποίηση του Φορέα;');">Διαγραφή</a>
            <button onclick="saveChanges()" 
            class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg dark:bg-indigo-600 dark:hover:bg-indigo-700 focus:outline-none dark:focus:ring-indigo-800">Αποθήκευση</button>
        </div>
        </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- Centered Pagination Controls -->
  <div class="flex justify-center items-center mt-6 space-x-2">
    <!-- Previous Page Link -->
    {% if page_obj.has_previous %}
        <a href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}" 
        class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 font-medium">
            Previous
        </a>
    {% else %}
        <span class="px-4 py-2 bg-gray-100 text-gray-400 rounded font-medium">Previous</span>
    {% endif %}

    <!-- Page Numbers with Limitation -->
    {% with total_pages=page_obj.paginator.num_pages %}
        {% if total_pages > 5 %}
            {% if page_obj.number > 3 %}
                <a href="?{{ request.GET.urlencode }}&page=1" 
                class="px-4 py-2 bg-gray-200 text-gray-700 font-medium rounded hover:bg-gray-300">
                    1
                </a>
                {% if page_obj.number > 4 %}
                    <span class="px-4 py-2 text-gray-500">...</span>
                {% endif %}
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if num >= page_obj.number|add:"-2" and num <= page_obj.number|add:"2" %}
                    {% if page_obj.number == num %}
                        <span class="px-4 py-2 bg-blue-700 text-white rounded font-medium">{{ num }}</span>
                    {% else %}
                        <a href="?{{ request.GET.urlencode }}&page={{ num }}" 
                        class="px-4 py-2 bg-gray-200 text-gray-700 font-medium rounded hover:bg-gray-300">
                            {{ num }}
                        </a>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.number < total_pages|add:"-2" %}
                {% if page_obj.number < total_pages|add:"-3" %}
                    <span class="px-4 py-2 text-gray-500">...</span>
                {% endif %}
                <a href="?{{ request.GET.urlencode }}&page={{ total_pages }}" 
                class="px-4 py-2 bg-gray-200 text-gray-700 font-medium rounded hover:bg-gray-300">
                    {{ total_pages }}
                </a>
            {% endif %}
        {% else %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <span class="px-4 py-2 bg-blue-700 text-white rounded font-medium">{{ num }}</span>
                {% else %}
                    <a href="?{{ request.GET.urlencode }}&page={{ num }}" 
                    class="px-4 py-2 bg-gray-200 text-gray-700 font-medium rounded hover:bg-gray-300">
                        {{ num }}
                    </a>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
  <!-- Next Page Link -->
    {% if page_obj.has_next %}
        <a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}" 
        class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 font-medium">
            Next
        </a>
    {% else %}
        <span class="px-4 py-2 bg-gray-100 text-gray-400 rounded font-medium">Next</span>
    {% endif %}

    <!-- Page Input Field -->
    <form method="GET" action="" class="flex items-center">
        <input type="number" name="page" min="1" max="{{ page_obj.paginator.num_pages }}" 
        class="w-16 px-2 py-1 text-center border border-gray-300 rounded" placeholder="{{ page_obj.number }}">
        <button type="submit" class="ml-2 px-4 py-2 bg-indigo-600 text-white rounded hover:bg-blue-600">
            Go
        </button>
    </form>
  </div>
</div>
<!--End Adeia List-->

<!--Adeia Modal-->
<div id="modal" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center {% if not show_modal %}hidden{% endif %}">
  <div class="bg-white rounded-lg p-6 w-full max-w-4xl">
      <!-- Close Button -->
      <div class="relative">
          <button id="closeModal" class="absolute font-bold text-2xl top-2 right-2 text-red-600 hover:text-red-700">
              &times;
          </button>
      </div>
      <h2 class="text-2xl text-indigo-600 font-semibold mb-4">Καταχώρηση άδειας</h2>
  <form method="post" id="modal-form">
      <div class="container max-w-screen-lg mx-auto">
          {% if messages %}
          <div class="space-y-4">
            {% for message in messages %}
            <div class="alert alert-success bg-green-100 border border-green-300 text-green-800 p-4 rounded-md">
              <p>{{ message }}</p>
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
      {% csrf_token %}
      <div class="mb-4 space-y-4">
          <!-- Field 1 -->
          <div>
              <label for="name" class="block text-sm font-medium text-gray-700 dark:text-white">ACS<span class="text-red-600 ml-2">*</span></label>
              {{form.acs_employee}} 
              {% if form.acs_employee.errors %}
              <div class="text-red-500 text-sm">{{ form.acs_employee.errors }}</div>
              {% endif %}
          </div>
      
          <!-- Field 2 -->
          <div>
              <label for="address" class="block text-sm font-medium text-gray-700 dark:text-white">Κατηγορία άδειας<span class="text-red-600 ml-2">*</span></label>
              {{form.adeiatype}} 
          </div>
      
          <!-- Field 3 -->
          <div>
              <label for="city" class="block text-sm font-medium text-gray-700 dark:text-white">Έναρξη άδειας<span class="text-red-600 ml-2">*</span></label>
              {{form.start_date}} 
          </div>

          <!-- Field 4 -->
          <div>
              <label for="phone" class="block text-sm font-medium text-gray-700 dark:text-white">Λήξη άδειας<span class="text-red-600 ml-2">*</span></label>
              {{form.end_date}} 
          </div>
                  <!-- Field 5 -->
          <div>
            <label for="phone" class="block text-sm font-medium text-gray-700 dark:text-white">Ημέρες άδειας<span class="text-red-600 ml-2">*</span></label>
            {{form.days}} 
          </div>
              
          <div class="flex justify-end mt-6">
              <button type="submit" class="px-4 py-2 w-full bg-green-600 hover:bg-green-700 font-semibold text-white rounded-lg">Αποθήκευση</button>
          </div>
          <p class="text-gray-700">* Στους υπολογισμούς εξαιρούνται οι αναρρωτικές άδειες.</p>
      </div>
  </form>
</div>
</div>
<!--End Organization Modal-->
<script>
  document.getElementById("openModal").addEventListener("click", () => {
      document.getElementById("modal").classList.remove("hidden");
  });
  
  document.getElementById("closeModal").addEventListener("click", () => {
      document.getElementById("modal").classList.add("hidden");
  });
  </script>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
        const modal = document.getElementById("modal");
        const form = document.getElementById("modal-form");
    
        form.addEventListener("submit", async (event) => {
            event.preventDefault();
    
            // Form submission
            const formData = new FormData(form);
            const response = await fetch(form.action, {
                method: "POST",
                body: formData,
            });
            const result = await response.json();
    
            if (result.success) {
                // Close modal on success
                modal.classList.add("hidden");
                alert("Form submitted successfully!");
            } else {
                // Keep modal open and show errors
                modal.classList.remove("hidden");
    
                // Display errors
                const errorMessages = document.getElementById("error-messages");
                errorMessages.innerHTML = "";
                for (const [field, errors] of Object.entries(result.errors)) {
                    const errorItem = document.createElement("div");
                    errorItem.className = "text-red-500";
                    errorItem.textContent = `${field}: ${errors.join(", ")}`;
                    errorMessages.appendChild(errorItem);
                }
            }
        });
    });
    </script>
    
    <!--Auto calculate-->
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        const startDateField = document.getElementById('id_start_date');
        const endDateField = document.getElementById('id_end_date');
        const daysField = document.getElementById('id_days');
      
        function calculateDays() {
            const startDate = new Date(startDateField.value);
            const endDate = new Date(endDateField.value);
      
            if (startDate && endDate && !isNaN(startDate) && !isNaN(endDate)) {
                const timeDiff = endDate - startDate;
                const days = Math.floor(timeDiff / (1000 * 60 * 60 * 24)) + 1; // Include both dates
                daysField.value = days > 0 ? days : 0;
            } else {
                daysField.value = '';
            }
        }
      
        startDateField.addEventListener('change', calculateDays);
        endDateField.addEventListener('change', calculateDays);
      });
      
      </script>
{% endblock %}

templates/apps/accounts/login.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>StudentFlow.gr</title>
<link href="{% static 'css/dist/styles.css' %}" rel="stylesheet">
  
</head>
<!-- component -->
<div class="bg-white flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm ">
    <h1 class="text-center text-5xl font-bold text-indigo-600 animate-bounce">
      ACS Services
    </h1>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-6" method="POST" action="{% url 'login' %}">
      {% csrf_token %}
        {% if form.errors %}
        <div id="error-message" class="alert alert-error" role="alert">
            {% for field in form %}
                {% for error in field.errors %}
                    <p class="font-bold text-white">{{ error }}</p>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
            {% endfor %}
        </div>
      {% endif %}
      <div>
        <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Email</label>
        <div class="mt-2">
          <input id="username" name="username"  required class="p-4 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>

      <div>
        <div class="flex items-center justify-between">
          <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
          <div class="text-sm">
            {% comment %} <a href="#" class="font-semibold text-indigo-600 hover:text-indigo-500">Ξεχάσατε τον κωδικό σας;</a> {% endcomment %}
          </div>
        </div>
        <div class="mt-2">
          <input id="password" name="password" type="password" autocomplete="off" required class="p-4 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>

      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Είσοδος</button>
      </div>
    </form>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
      const successMessage = document.getElementById('error-message');
      if (successMessage) {
          setTimeout(function() {
              successMessage.style.opacity = 0;
              setTimeout(function() {
                  successMessage.style.display = 'none';
              }, 600); // Matches the CSS transition time
          }, 2000); //  seconds
      }
  });
</script>